name: Pipe

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          pip install pyinstaller
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
          
      - name: Build Java
        run:  mvn -f pom.xml test
        
      - name: Piping Java and Python
        run : mvn compile exec:java -Dexec.mainClass="sender.BMSSender.java" | python receiver/receiver_test.py
